=== IlyaMatsuev/Java-labs/lab3_4/files/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pages" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="cost" type="xs:int" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="material" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IlyaMatsuev/Java-labs/lab3_4/files/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" version="2.0" href = "books.xsl"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <pages>123</pages>
        <cost>5000</cost>
        <material>CARTOON</material>
    </book>
    <book>
        <pages>43</pages>
        <cost>900</cost>
        <material>PAPER</material>
    </book>
    <book>
        <pages>233</pages>
        <cost>11133</cost>
        <material>LEATHER</material>
    </book>
</books>
